// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZueaMl82gkpdLuSLvF7xyizLGl1CSNM8',
    appId: '1:1030717588718:web:7ee5497fcf007734a3dfff',
    messagingSenderId: '1030717588718',
    projectId: 'week-5-tutorial-6677c',
    authDomain: 'week-5-tutorial-6677c.firebaseapp.com',
    storageBucket: 'week-5-tutorial-6677c.firebasestorage.app',
    measurementId: 'G-QVZVX2VZCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxQ9Qf9IrxmWvGI2Bxwb1y2ToHxmx1H50',
    appId: '1:1030717588718:android:e3ed48c5ce6d6b36a3dfff',
    messagingSenderId: '1030717588718',
    projectId: 'week-5-tutorial-6677c',
    storageBucket: 'week-5-tutorial-6677c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhHryNm7Yg01ChW5hcXRoR67KOL35Uy7w',
    appId: '1:1030717588718:ios:e268f67c9115671da3dfff',
    messagingSenderId: '1030717588718',
    projectId: 'week-5-tutorial-6677c',
    storageBucket: 'week-5-tutorial-6677c.firebasestorage.app',
    iosBundleId: 'com.example.tutorial13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZueaMl82gkpdLuSLvF7xyizLGl1CSNM8',
    appId: '1:1030717588718:web:276858996c338ef4a3dfff',
    messagingSenderId: '1030717588718',
    projectId: 'week-5-tutorial-6677c',
    authDomain: 'week-5-tutorial-6677c.firebaseapp.com',
    storageBucket: 'week-5-tutorial-6677c.firebasestorage.app',
    measurementId: 'G-K6PFBRPWG5',
  );
}
